-- ตาราง activity_registrations สำหรับเก็บข้อมูลผู้ลงทะเบียนกิจกรรม
-- ฟิลด์: ชื่อ-นามสกุล, อีเมล, เบอร์โทร, บริษัท, ชื่อกิจกรรม, วันเวลาที่ลงทะเบียน

CREATE TABLE IF NOT EXISTS activity_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT NOT NULL,
  activity_name TEXT DEFAULT 'กิจกรรม MindDoJo',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- เปิดใช้งาน Row Level Security (RLS)
ALTER TABLE activity_registrations ENABLE ROW LEVEL SECURITY;

-- 1) อนุญาตให้บุคคลทั่วไป (Public / Anon) ส่งฟอร์มลงทะเบียนได้
DROP POLICY IF EXISTS "Allow public insert activity_registrations" ON activity_registrations;
CREATE POLICY "Allow public insert activity_registrations"
  ON activity_registrations
  FOR INSERT
  WITH CHECK (true);

-- 2) อนุญาตให้บุคคลทั่วไปอ่านข้อมูลได้ (สำหรับแสดงผล/ยืนยัน)
DROP POLICY IF EXISTS "Allow public read activity_registrations" ON activity_registrations;
CREATE POLICY "Allow public read activity_registrations"
  ON activity_registrations
  FOR SELECT
  USING (true);

-- 3) อนุญาตให้ Authenticated User (Admin) จัดการ ลบ หรือแก้ไขข้อมูลได้
DROP POLICY IF EXISTS "Allow authenticated manage activity_registrations" ON activity_registrations;
CREATE POLICY "Allow authenticated manage activity_registrations"
  ON activity_registrations
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- ดัชนีเพื่อค้นหาและเรียงลำดับได้เร็ว
CREATE INDEX IF NOT EXISTS idx_activity_registrations_created_at ON activity_registrations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_registrations_email ON activity_registrations(email);
CREATE INDEX IF NOT EXISTS idx_activity_registrations_company ON activity_registrations(company);
