create table if not exists public.peer_feedback_participants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.peer_feedback_audience_grid (
  id bigint generated by default as identity primary key,
  evaluator_name text,
  presenter_team text not null,
  answer_first_score integer not null,
  logic_score integer not null,
  story_score integer not null,
  delivery_score integer not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.peer_feedback_audience_grid
  add column if not exists evaluator_name text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'peer_feedback_audience_grid'
      and column_name = 'evaluator_team'
  ) then
    update public.peer_feedback_audience_grid
      set evaluator_name = coalesce(evaluator_name, evaluator_team)
      where evaluator_name is null;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'peer_feedback_audience_grid_answer_first_score_range'
  ) then
    alter table public.peer_feedback_audience_grid
      add constraint peer_feedback_audience_grid_answer_first_score_range
      check (answer_first_score between 1 and 5) not valid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'peer_feedback_audience_grid_logic_score_range'
  ) then
    alter table public.peer_feedback_audience_grid
      add constraint peer_feedback_audience_grid_logic_score_range
      check (logic_score between 1 and 5) not valid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'peer_feedback_audience_grid_story_score_range'
  ) then
    alter table public.peer_feedback_audience_grid
      add constraint peer_feedback_audience_grid_story_score_range
      check (story_score between 1 and 5) not valid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'peer_feedback_audience_grid_delivery_score_range'
  ) then
    alter table public.peer_feedback_audience_grid
      add constraint peer_feedback_audience_grid_delivery_score_range
      check (delivery_score between 1 and 5) not valid;
  end if;
end $$;

create index if not exists peer_feedback_audience_grid_presenter_team_idx
  on public.peer_feedback_audience_grid (presenter_team);

create index if not exists peer_feedback_audience_grid_created_at_idx
  on public.peer_feedback_audience_grid (created_at desc);

create index if not exists peer_feedback_participants_name_idx
  on public.peer_feedback_participants (name);

alter table public.peer_feedback_participants enable row level security;
alter table public.peer_feedback_audience_grid enable row level security;

grant insert, select on public.peer_feedback_participants to anon, authenticated;
grant insert, select on public.peer_feedback_audience_grid to anon, authenticated;

drop policy if exists "Allow public insert peer feedback participants"
  on public.peer_feedback_participants;

create policy "Allow public insert peer feedback participants"
  on public.peer_feedback_participants
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Allow public read peer feedback participants"
  on public.peer_feedback_participants;

create policy "Allow public read peer feedback participants"
  on public.peer_feedback_participants
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Allow public insert peer feedback audience grid"
  on public.peer_feedback_audience_grid;

create policy "Allow public insert peer feedback audience grid"
  on public.peer_feedback_audience_grid
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Allow public read peer feedback audience grid"
  on public.peer_feedback_audience_grid;

create policy "Allow public read peer feedback audience grid"
  on public.peer_feedback_audience_grid
  for select
  to anon, authenticated
  using (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.peer_feedback_participants;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.peer_feedback_audience_grid;
  exception
    when duplicate_object then null;
  end;
end $$;
