insert into storage.buckets (id, name, public)
values ('innoclub-second-videos', 'innoclub-second-videos', true)
on conflict (id) do update set public = true;

create table if not exists public.innoclub_second_videos (
  id bigint generated by default as identity primary key,
  team_name text not null,
  title text not null,
  description text,
  video_url text not null,
  storage_path text,
  file_name text,
  file_size bigint,
  mime_type text,
  created_at timestamptz not null default now()
);

create index if not exists innoclub_second_videos_created_at_idx
  on public.innoclub_second_videos (created_at desc);

create index if not exists innoclub_second_videos_team_name_idx
  on public.innoclub_second_videos (team_name);

alter table public.innoclub_second_videos enable row level security;

grant insert, select, delete on public.innoclub_second_videos to anon, authenticated;

drop policy if exists "Allow public insert innoclub second videos"
  on public.innoclub_second_videos;

create policy "Allow public insert innoclub second videos"
  on public.innoclub_second_videos
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Allow public read innoclub second videos"
  on public.innoclub_second_videos;

create policy "Allow public read innoclub second videos"
  on public.innoclub_second_videos
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Allow public delete innoclub second videos"
  on public.innoclub_second_videos;

create policy "Allow public delete innoclub second videos"
  on public.innoclub_second_videos
  for delete
  to anon, authenticated
  using (true);

drop policy if exists "Allow public upload innoclub second video files"
  on storage.objects;

create policy "Allow public upload innoclub second video files"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'innoclub-second-videos');

drop policy if exists "Allow public read innoclub second video files"
  on storage.objects;

create policy "Allow public read innoclub second video files"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'innoclub-second-videos');

drop policy if exists "Allow public delete innoclub second video files"
  on storage.objects;

create policy "Allow public delete innoclub second video files"
  on storage.objects
  for delete
  to anon, authenticated
  using (bucket_id = 'innoclub-second-videos');

do $$
begin
  begin
    alter publication supabase_realtime add table public.innoclub_second_videos;
  exception
    when duplicate_object then null;
  end;
end $$;
